### ISSUE TITLE
[Feature Request] Show subtasks on task status page

### ISSUE THREAD

**Issue by bartvanb** [vantage6/vantage6-UI#148]
**Problem description**
When a task is in progress, the task detail page shows which algorithm containers are running. However, subtasks are not yet included there.

**Desired solution**
Show the status of new algorithm containers when they are started up.

**Additional context**
Depends on #137

**Comment by bartvanb** [comment]
This depends on knowing the subtasks, which may be obtained either from the API by polling or via the socket connection (#84). The socket is the preferred solution as we ultimately want that to be implemented over polling

**Comment by bartvanb** [comment]
- [ ] Show subtasks on status part
- [ ] Include link to go to child page
- [ ] Include link to go to parent page
